name: input
on:
  workflow_dispatch:
    inputs:
      a:
        
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.a }}
      - run: test ${{ secrets.FLAG }}
