name: js injection

on:
  pull_request_target:

jobs:
  a:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            console.log("${{ github.event.pull_request.title }}")
