name: js injection

on:
  workflow_dispatch:
    inputs:
      a:

jobs:
  a:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            console.log("${{ github.inputs.a }}")
